### ISSUE TITLE
TypeError: (intermediate value)(intermediate value)(intermediate value).default.extend is not a function

### ISSUE THREAD

**Issue by ronst22** [devboell/react-fretboard#5]
×
TypeError: (intermediate value)(intermediate value)(intermediate value).default.extend is not a function
srcComponentsFretboardSkinsFretWrapperBoxesJs
node_modules/react-fretboard/dist/react-fretboard.js:5017
  5014 | 
  5015 | var a = ((r = c) && r.__esModule ? r : {
  5016 |   default: r
> 5017 | }).default.extend(o, function (n) {
       | ^  5018 |   return e = (t = n).color, t.isHighlighted && (0, i.css)(u, e);
  5019 |   var t, e;
  5020 | });
View compiled
e
node_modules/react-fretboard/dist/react-fretboard.js:12
   9 |     l: !1,
  10 |     exports: {}
  11 |   };
> 12 |   return n[r].call(u.exports, u, u.exports, e), u.l = !0, u.exports;
     | ^  13 | }
  14 | 
  15 | return e.m = n, e.c = t, e.d = function (n, t, r) {
View compiled
srcComponentsFretboardSkinsSkinsJs
node_modules/react-fretboard/dist/react-fretboard.js:5125
  5122 |     u = a(e("./src/components/Fretboard/Skins/BoardGraphicStrings/index.js")),
  5123 |     o = a(e("./src/components/Fretboard/Skins/NutGraphicBoxes/index.js")),
  5124 |     i = a(e("./src/components/Fretboard/Skins/NutGraphicStrings/index.js")),
> 5125 |     c = a(e("./src/components/Fretboard/Skins/FretWrapperBoxes.js")),
       | ^  5126 |     s = a(e("./src/components/Fretboard/Skins/FretWrapperStrings.js"));
  5127 | 
  5128 | function a(n) {
View compiled
e
node_modules/react-fretboard/dist/react-fretboard.js:12
   9 |     l: !1,
  10 |     exports: {}
  11 |   };
> 12 |   return n[r].call(u.exports, u, u.exports, e), u.l = !0, u.exports;
     | ^  13 | }
  14 | 
  15 | return e.m = n, e.c = t, e.d = function (n, t, r) {
View compiled
srcComponentsFretboardNeckPositionFretIndexJs
node_modules/react-fretboard/dist/react-fretboard.js:4456
  4453 | c = e("styled-components"),
  4454 | s = e("./src/lib/shapes.js"),
  4455 | a = e("./src/lib/fret.js"),
> 4456 | f = e("./src/components/Fretboard/Skins/skins.js"),
       | ^  4457 | l = p(e("./src/components/Fretboard/Neck/Position/Fret/Content/index.js")),
  4458 | d = p(e("./src/components/Fretboard/Neck/Position/Fret/Wrapper.js"));
  4459 | 
View compiled
e
node_modules/react-fretboard/dist/react-fretboard.js:12
   9 |     l: !1,
  10 |     exports: {}
  11 |   };
> 12 |   return n[r].call(u.exports, u, u.exports, e), u.l = !0, u.exports;
     | ^  13 | }
  14 | 
  15 | return e.m = n, e.c = t, e.d = function (n, t, r) {
View compiled
srcComponentsFretboardNeckPositionIndexJs
node_modules/react-fretboard/dist/react-fretboard.js:4596
  4593 |     i = e("./node_modules/ramda/es/index.js"),
  4594 |     c = e("./src/lib/tonal-helpers.js"),
  4595 |     s = f(e("./src/components/Fretboard/Neck/Position/Wrapper.js")),
> 4596 |     a = f(e("./src/components/Fretboard/Neck/Position/Fret/index.js"));
       | ^  4597 | 
  4598 | function f(n) {
  4599 |   return n && n.__esModule ? n : {
View compiled
e
node_modules/react-fretboard/dist/react-fretboard.js:12
   9 |     l: !1,
  10 |     exports: {}
  11 |   };
> 12 |   return n[r].call(u.exports, u, u.exports, e), u.l = !0, u.exports;
     | ^  13 | }
  14 | 
  15 | return e.m = n, e.c = t, e.d = function (n, t, r) {
View compiled
srcComponentsFretboardNeckOpenPositionIndexJs
node_modules/react-fretboard/dist/react-fretboard.js:4218
  4215 | });
  4216 | var r = c(e("react")),
  4217 |     u = c(e("./node_modules/prop-types/index.js")),
> 4218 |     o = c(e("./src/components/Fretboard/Neck/Position/index.js")),
       | ^  4219 |     i = c(e("./src/components/Fretboard/Neck/ViewPort/index.js"));
  4220 | 
  4221 | function c(n) {
View compiled
e
node_modules/react-fretboard/dist/react-fretboard.js:12
   9 |     l: !1,
  10 |     exports: {}
  11 |   };
> 12 |   return n[r].call(u.exports, u, u.exports, e), u.l = !0, u.exports;
     | ^  13 | }
  14 | 
  15 | return e.m = n, e.c = t, e.d = function (n, t, r) {
View compiled
srcComponentsFretboardNeckIndexJs
node_modules/react-fretboard/dist/react-fretboard.js:4738
  4735 | var r = a(e("react")),
  4736 |     u = a(e("./node_modules/prop-types/index.js")),
  4737 |     o = a(e("./src/components/Fretboard/Neck/ViewPortMain/index.js")),
> 4738 |     i = a(e("./src/components/Fretboard/Neck/OpenPosition/index.js")),
       | ^  4739 |     c = a(e("./src/components/Fretboard/Neck/Nut/index.js")),
  4740 |     s = a(e("./src/components/Fretboard/Neck/Board/index.js"));
  4741 | 
View compiled
e
node_modules/react-fretboard/dist/react-fretboard.js:12
   9 |     l: !1,
  10 |     exports: {}
  11 |   };
> 12 |   return n[r].call(u.exports, u, u.exports, e), u.l = !0, u.exports;
     | ^  13 | }
  14 | 
  15 | return e.m = n, e.c = t, e.d = function (n, t, r) {
View compiled
srcComponentsFretboardIndexJs
node_modules/react-fretboard/dist/react-fretboard.js:5202
  5199 | s = h(e("./src/themes/fretboard-theme.js")),
  5200 | a = e("./src/lib/shapes.js"),
  5201 | f = e("./src/lib/fretboard.js"),
> 5202 | l = h(e("./src/components/Fretboard/Neck/index.js")),
       | ^  5203 | d = h(e("./src/components/Fretboard/PositionLabels/index.js")),
  5204 | p = h(e("./src/components/Fretboard/Wrapper.js"));
  5205 | 
View compiled
e
node_modules/react-fretboard/dist/react-fretboard.js:12
   9 |     l: !1,
  10 |     exports: {}
  11 |   };
> 12 |   return n[r].call(u.exports, u, u.exports, e), u.l = !0, u.exports;
     | ^  13 | }
  14 | 
  15 | return e.m = n, e.c = t, e.d = function (n, t, r) {
View compiled
srcIndexJs
node_modules/react-fretboard/dist/react-fretboard.js:5343
  5340 |     return r.scaleNotes;
  5341 |   }
  5342 | });
> 5343 | var u = e("./src/components/Fretboard/index.js");
       | ^  5344 | Object.defineProperty(t, "default", {
  5345 |   enumerable: !0,
  5346 |   get: function get() {
View compiled
e
node_modules/react-fretboard/dist/react-fretboard.js:12
   9 |     l: !1,
  10 |     exports: {}
  11 |   };
> 12 |   return n[r].call(u.exports, u, u.exports, e), u.l = !0, u.exports;
     | ^  13 | }
  14 | 
  15 | return e.m = n, e.c = t, e.d = function (n, t, r) {
View compiled
push../node_modules/react-fretboard/dist/react-fretboard.js.module.exports../node_modules/fbjs/lib/emptyFunction.js
node_modules/react-fretboard/dist/react-fretboard.js:34
  31 |     return e.d(t, "a", t), t;
  32 |   }, e.o = function (n, t) {
  33 |     return Object.prototype.hasOwnProperty.call(n, t);
> 34 |   }, e.p = "", e(e.s = "./src/index.js");
  35 | }({
  36 |   "./node_modules/fbjs/lib/emptyFunction.js": function node_modulesFbjsLibEmptyFunctionJs(n, t, e) {
  37 |     "use strict";
View compiled
./node_modules/react-fretboard/dist/react-fretboard.js
node_modules/react-fretboard/dist/react-fretboard.js:35
  32 |   }, e.o = function (n, t) {
  33 |     return Object.prototype.hasOwnProperty.call(n, t);
  34 |   }, e.p = "", e(e.s = "./src/index.js");
> 35 | }({
  36 |   "./node_modules/fbjs/lib/emptyFunction.js": function node_modulesFbjsLibEmptyFunctionJs(n, t, e) {
  37 |     "use strict";
  38 | 
View compiled
__webpack_require__
/home/ron/projects/guitar-react/my-app/webpack/bootstrap:782
  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;
View compiled
fn
/home/ron/projects/guitar-react/my-app/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module../src/App.js
http://localhost:3000/static/js/main.chunk.js:33:73
__webpack_require__
/home/ron/projects/guitar-react/my-app/webpack/bootstrap:782
  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;
View compiled
fn
/home/ron/projects/guitar-react/my-app/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module../src/index.js
http://localhost:3000/static/js/main.chunk.js:158:62
__webpack_require__
/home/ron/projects/guitar-react/my-app/webpack/bootstrap:782
  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;
View compiled
fn
/home/ron/projects/guitar-react/my-app/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
0
http://localhost:3000/static/js/main.chunk.js:285:18
__webpack_require__
/home/ron/projects/guitar-react/my-app/webpack/bootstrap:782
  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;
View compiled
checkDeferredModules
/home/ron/projects/guitar-react/my-app/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | return result;
View compiled
Array.webpackJsonpCallback [as push]
/home/ron/projects/guitar-react/my-app/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://localhost:3000/static/js/main.chunk.js:1:57
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by devboell** [comment]
Hi there, thanks for reporting. From what you copy/pasted here I cannot see what's going on. Can you show me how you configured the fretboard? What props are you passing?

**Comment by tomekr** [comment]
Hi @devboell, I get the same message by attempting to just use the basic example of:

```
  <div>
    <Fretboard
      skinType="strings"
      selectedNotes={['C3', 'E3', 'G3']}
    />
  </div>
```

To reproduce:

1. `create-react-app fretboard-test`
2. `cd fretboard-test`
3. `npm install react-fretboard`
4. `npm install styled-components`
5. Use the example from the Readme

```
import Fretboard, { chordNotes } from 'react-fretboard'
import './App.css';

function App() {
  return (
    <div className="App">
      <div>
        <Fretboard
          skinType="strings"
          selectedNotes={['C3', 'E3', 'G3']}
        />
      </div>
    </div>
  );
}

export default App;
```
6. `npm start`
7. Visit http://localhost:3000/
8. You should see the error.

<img width="1047" alt="Screen Shot 2019-11-09 at 8 40 03 AM" src="https://user-images.githubusercontent.com/723637/68530280-96836980-02cc-11ea-8b4c-1e0d337ba974.png">

**Comment by tomekr** [comment]
It looks like downgrading the `styled-components` dependency fixes the issue. Running `npm install syled-components` added `"styled-components": "^4.4.1",` to `package.json`. I replaced this with `"styled-components": "^3.2.3",` and re-ran `npm install` to make the error go away.
