### ISSUE TITLE
Cant get fretboard working

### ISSUE THREAD

**Issue by alecferko** [devboell/react-fretboard#8]
I am having issues getting the fretboard working. I install fretboard, install styled-components, and then i get "TypeError: (intermediate value)(intermediate value)(intermediate value).default.extend is not a function" with reference to a file thousands of lines long. I cant find any information on this error anywhere, and I've tried this in typescript projects, regular projects and completely fresh projects. Any Ideas?

**Comment by devboell** [comment]
Hi there, my guess would be that you installed a recent version of styled-components. There was an api change where they deprecated `extend` (see https://styled-components.com/docs/faqs, 'What do I need to do to migrate to v4?')

I have not updated this project for a long time, so I am afraid `react-fretboard` will only work with an older version of styled-components.

I see in the react-fretboard-demo repo that I use `"styled-components": "^2.2.1"`. Could you try it with that version?

**Comment by alecferko** [comment]
That worked, thank you so much for the quick response!
